title: James Halsall

owner:
  email: james.t.halsall@googlemail.com
  name: James Halsall
  twitter: JamesHalsall

baseurl: ""
url: "http://jameshalsall.github.io"
comments: true

permalink: /posts/:slug

links:
  - title: Github
    url: https://github.com/jameshalsall
    external: true
  - title: Twitter
    url: http://twitter.com/jameshalsall
    external: true
  - title: Stack Overflow
    url: http://stackoverflow.com/users/603256/jameshalsall
    external: true

timezone:    Europe/London
future:      true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

sass:
    style: :compressed
